### ISSUE TITLE
Default value programmatically

### ISSUE THREAD

**Issue by danielghre** [chicio/RangeUISlider#11]
Hi, is it possible to set values programmatically ? I tried this 

```
ageSlider.delegage = self
ageSlider.defaultValueLeftKnob = 20
ageSlider.defaultValueRightKnob = 33
```

but it seems to have an error : 'defaultValueLeftKnob' is inaccessible due to 'internal' protection level'

Thank you for any help !

**Comment by chicio** [comment]
Hi @danielghre,
no, it is not possible to set the default value programmatically.
You receive that error because the properties your trying to set are not public (but have default access modifier that on swift is internal, so at module level). I designed RangeUISlider to be completely customizable with Interface Builder, but maybe could be good to be able to set the default values for the knobs programmatically. If you want you can modify and open a pull request or I can work on that in the next days.
Let me know.
Thanks,
Fabrizio.

**Comment by danielghre** [comment]
Thank you for your answer, yeah It would be awesome if you could work on that in the bext few days ! 
Keep me inform,
Thank you so much 
Daniel

**Comment by chicio** [comment]
Hi @danielghre,
I release a new version (also on Cocoapods) of RangeUISlider that lets you set programmatically the following values:
- scaleMinValue
- scaleMaxValue
- defaultValueLeftKnob
- defaultValueRightKnob

You can find an example in the demo app on [this controller](https://github.com/chicio/RangeUISlider/blob/master/Demo/SetupProgrammaticViewController.swift "example programmatic setup"). You have to do something like this in your code:

```swift
ageSlider.scaleMinValue = 0 //If you don't set any value the default is 0
ageSlider.scaleMaxValue = 100 //If you don't set any value the default is 1
ageSlider.defaultValueLeftKnob = 35 //If the scale is the default one insert a value between 0         
ageSlider.defaultValueRightKnob = 75 //If the scale is the default one insert a value between 0 
```

Let me know if you have any trouble. For me the issue is closed.
Keep supporting my work by starring my repos!! 😃 

Thanks.
Fabrizio.

**Comment by NikhilManapure** [comment]
@chicio UI doesn't seem to be updating when we update the `slider.defaultValueLeftKnob`. Will you please help me with this?

**Comment by chicio** [comment]
Hi @NikhilManapure , can you share more details about your problem like Xcode version, iOS version and the piece of code that is not working?
