### ISSUE TITLE
Issue when change dynamically defaultValueLeftKnob and defaultValueRightKnob

### ISSUE THREAD

**Issue by TofPlay** [chicio/RangeUISlider#36]
**Describe the bug**
I will want to dynamically initialize `defaultValueLeftKnob` and `defaultValueRightKnob`

**To Reproduce**
In a `viewDidLoad`:
```swift
slideRange.rangeSelectedColor = .red
slideRange.rangeNotSelectedColor = UIColor.lightGray.withAlphaComponent(0.5)
slideRange.leftKnobWidth = 20
slideRange.leftKnobHeight = 20
slideRange.leftKnobCorners = 10
slideRange.leftKnobColor = .red
slideRange.rightKnobWidth = 20
slideRange.rightKnobHeight = 20
slideRange.rightKnobCorners = 10
slideRange.rightKnobColor = .red
slideRange.delegate = self
```
Change dynamically after a callback in the main thread:
```swift
slideRange.defaultValueLeftKnob = 13.70   // example of value
slideRange.defaultValueLeftKnob = 17.50  // example of value

slideRange.scaleMinValue = 10   // example of value
slideRange.scaleMaxValue = 20  // example of value
```
**Expected behavior**
Display Knobs at the right place when I initialize `defaultValueLeftKnob` and `defaultValueRightKnob`
Screenshots (2) and (3) must be the same

**Screenshots**
(1) Initial state 
![image](https://user-images.githubusercontent.com/1082222/107960223-a47e6a80-6fa4-11eb-9ccc-3a7046a74c32.png)

(2) Select values
![image](https://user-images.githubusercontent.com/1082222/107960771-51f17e00-6fa5-11eb-8684-d5bd7b226ea2.png)

(3) By initialize `defaultValueLeftKnob` and `defaultValueRightKnob`
![image](https://user-images.githubusercontent.com/1082222/107960587-1bb3fe80-6fa5-11eb-8c93-7f7787b28e1a.png)

**Device (please complete the following information):**
 - Model: iPhone Xr
 - OS: 14.4

**Additional context**
UIKit application 
Define RangeUISlider in a Storyboard
Same with `changeLeftKnob` and `changeRightKnob`

**Comment by chicio** [comment]
Hi @TofPlay ,

thanks (again for your feedback). I will investigate as soon as possible the problem.

PS remember to support my work by ⭐️ starring ⭐️ my repository

**Comment by chicio** [comment]
Hi @TofPlay ,

I opened a MR with the fix. Can you check/test it and provide some feedback if it works as expected? 
I already added some UI/integration tests but I want also your approval.
In any case I will eventually merge in the next days.

Thanks,
Fabrizio.

**Comment by TofPlay** [comment]
Hi @chicio,

Fix `defaultValueRightKnob` not `defaultValueLeftKnob` because `isValidForLeftKnob` method return `false` 
![image](https://user-images.githubusercontent.com/1082222/108031927-ec979e80-7031-11eb-88dc-7b18176e24ae.png)

**Comment by chicio** [comment]
@TofPlay are you sure you're setting a valid value for the left knob with respect to the scale?? Because if you look at the demo app inside RangeUISlider you can find a new screen where I'm testing the fix and it works for both knob (see video below).

https://user-images.githubusercontent.com/4048413/108033894-f969c180-7034-11eb-8f71-1f694e532f20.mov

Remember also that **you have to set the `defaultValueRightKnob` not `defaultValueLeftKnob` AFTER you set new scale** (because the checks contained in the `isValid...Knob` are done using the scale values). Have a look at the new demo controller [ChangeKnobsProgrammaticViewController](https://github.com/chicio/RangeUISlider/blob/67aa24cd477c1e0214622063aa1448a57290741c/RangeUISliderDemo/ChangeDefaultKnobsValuesProgrammaticViewController.swift) to see a usage example. 
If it doesn't work, can you share more details about how are you using RangeUISlider? Let me know if the information above solves your problems.

**Comment by chicio** [comment]
@TofPlay any news? I tested a lot the feature again it seems fine to me. I'm going to merge in a between today and tomorrow. Thanks.

**Comment by TofPlay** [comment]
@chicio sorry I'm busy with other higher priority tasks. I don't have time to really test. For the moment your component has been removed from the project. We will look at it again when we resume the functionality that uses it.

**Comment by chicio** [comment]
Ok @TofPlay no problem. So I will merge it and release a new version (that you can test later). Thank you @TofPlay
