### ISSUE TITLE
Can't reset min value

### ISSUE THREAD

**Issue by vfumin** [chicio/RangeUISlider#46]
https://gyazo.com/716c5a49744f21ae5df8bee592cd7687

I found some errors in code

**Comment by vfumin** [comment]
Hello! When can you fix this issue?

**Comment by chicio** [comment]
Hi @vfumin ,

sorry for the late reply. During the last weeks have been busy with another project (a new SwiftUI library https://github.com/chicio/TabBarUIAction), and I still some other stuff to do before come back to RangeUISlider. If you want you can open a MR with the fix so that I can review and eventually merge it. Thanks for your understanding.

Fabrizio

**Comment by chicio** [comment]
Resolved by #49
